spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
    password: ${SPRING_DATASOURCE_USERNAME:postgres}
    username: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:flyway/
    sql-migration-prefix: V-
    sql-migration-separator: __
    schemas: hops
    table: schema_history